on:
  push:
    tags:
      - "*"

name: Build & Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo build --release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/wlprobe
